<?xml version='1.0' encoding='UTF-8'?>
<project xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://maven.apache.org/POM/4.0.0">
    <modelVersion>4.0.0</modelVersion>
    <groupId>org.capnproto</groupId>
    <artifactId>capnp-jvm</artifactId>
    <packaging>pom</packaging>
    <version>${revision}</version>
    <name>Cap'n Proto for Java</name>
    <url>https://capnproto.org/</url>
    <organization>
        <name>org.capnproto</name>
    </organization>
    <modules>
      <module>capnp-jvm-core</module>
      <module>capnp-jvm-serialization</module>
      <module>capnp-jvm-serialization-bytebuffer</module>
      <module>capnp-jvm-serialization-ffm</module>
      <module>compiler</module>
      <module>examples</module>
      <module>benchmark</module>
    </modules>
    <licenses>
        <license>
            <name>MIT</name>
            <url>http://opensource.org/licenses/MIT</url>
            <distribution>repo</distribution>
        </license>
    </licenses>
    <scm>
        <url>git@github.com:jayfeng0625/capnp-jvm.git</url>
        <connection>scm:git@github.com:jayfeng0625/capnp-jvm.git</connection>
        <developerConnection>scm:git@github.com:jayfeng0625/capnp-jvm.git</developerConnection>
    </scm>
    <developers>
        <developer>
            <id>dwrensha</id>
            <name>David Renshaw</name>
            <url>https://github.com/dwrensha</url>
        </developer>
        <developer>
            <id>jayfeng0625</id>
            <name>Jay Feng</name>
            <url>https://github.com/jayfeng0625</url>
        </developer>
    </developers>

    <properties>
      <revision>0.2.0-SNAPSHOT</revision>
      <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
      <maven.compiler.release>25</maven.compiler.release>
      <child.project.url.inherit.append.path>false</child.project.url.inherit.append.path>
      <child.scm.url.inherit.append.path>false</child.scm.url.inherit.append.path>
      <child.scm.connection.inherit.append.path>false</child.scm.connection.inherit.append.path>
      <child.scm.developerConnection.inherit.append.path>false</child.scm.developerConnection.inherit.append.path>
    </properties>

    <distributionManagement>
      <snapshotRepository>
        <id>ossrh</id>
        <url>https://oss.sonatype.org/content/repositories/snapshots</url>
      </snapshotRepository>
      <repository>
        <id>ossrh</id>
        <url>https://oss.sonatype.org/service/local/staging/deploy/maven2/</url>
      </repository>
    </distributionManagement>

    <dependencyManagement>
      <dependencies>
        <dependency>
          <groupId>org.capnproto</groupId>
          <artifactId>capnp-jvm-core</artifactId>
          <version>${project.version}</version>
        </dependency>
        <dependency>
          <groupId>org.capnproto</groupId>
          <artifactId>capnp-jvm-serialization</artifactId>
          <version>${project.version}</version>
        </dependency>
        <dependency>
          <groupId>org.capnproto</groupId>
          <artifactId>capnp-jvm-serialization-bytebuffer</artifactId>
          <version>${project.version}</version>
        </dependency>
        <dependency>
          <groupId>org.capnproto</groupId>
          <artifactId>capnp-jvm-serialization-ffm</artifactId>
          <version>${project.version}</version>
        </dependency>
        <dependency>
          <groupId>org.junit.jupiter</groupId>
          <artifactId>junit-jupiter</artifactId>
          <version>5.11.4</version>
          <scope>test</scope>
        </dependency>
      </dependencies>
    </dependencyManagement>

    <build>
      <plugins>
        <plugin>
          <groupId>org.codehaus.mojo</groupId>
          <artifactId>flatten-maven-plugin</artifactId>
          <version>1.6.0</version>
          <configuration>
            <updatePomFile>true</updatePomFile>
            <flattenMode>resolveCiFriendliesOnly</flattenMode>
          </configuration>
          <executions>
            <execution>
              <id>flatten</id>
              <phase>process-resources</phase>
              <goals>
                <goal>flatten</goal>
              </goals>
            </execution>
            <execution>
              <id>flatten.clean</id>
              <phase>clean</phase>
              <goals>
                <goal>clean</goal>
              </goals>
            </execution>
          </executions>
        </plugin>
      </plugins>
      <pluginManagement>
        <plugins>
          <plugin>
            <groupId>org.apache.maven.plugins</groupId>
            <artifactId>maven-compiler-plugin</artifactId>
            <version>3.15.0</version>
            <configuration>
              <compilerArgument>-Xlint:unchecked</compilerArgument>
            </configuration>
          </plugin>
          <plugin>
            <artifactId>maven-antrun-plugin</artifactId>
            <version>3.2.0</version>
          </plugin>
          <plugin>
            <groupId>org.codehaus.mojo</groupId>
            <artifactId>build-helper-maven-plugin</artifactId>
            <version>3.6.1</version>
          </plugin>
        </plugins>
      </pluginManagement>
    </build>

    <profiles>
      <profile>
        <id>release</id>
        <build>
          <plugins>
            <plugin>
              <groupId>org.apache.maven.plugins</groupId>
              <artifactId>maven-source-plugin</artifactId>
              <version>2.2.1</version>
              <executions>
                <execution>
                  <id>attach-sources</id>
                <goals>
                  <goal>jar-no-fork</goal>
                </goals>
              </execution>
            </executions>
          </plugin>
          <plugin>
            <groupId>org.apache.maven.plugins</groupId>
            <artifactId>maven-javadoc-plugin</artifactId>
            <version>2.10.3</version>
            <executions>
              <execution>
                <id>attach-javadocs</id>
                <goals>
                  <goal>jar</goal>
                </goals>
                <configuration>
                  <failOnError>false</failOnError>
                </configuration>
              </execution>
            </executions>
          </plugin>
          <plugin>
            <artifactId>maven-gpg-plugin</artifactId>
            <version>1.6</version>
            <executions>
              <execution>
                <id>sign-artifacts</id>
                <phase>verify</phase>
                <goals>
                  <goal>sign</goal>
                </goals>
              </execution>
            </executions>
          </plugin>
          <plugin>
            <groupId>org.sonatype.plugins</groupId>
            <artifactId>nexus-staging-maven-plugin</artifactId>
            <version>1.6.6</version>
            <extensions>true</extensions>
            <configuration>
              <serverId>ossrh</serverId>
              <nexusUrl>https://oss.sonatype.org/</nexusUrl>
              <autoReleaseAfterClose>true</autoReleaseAfterClose>
            </configuration>
          </plugin>
        </plugins>
      </build>
    </profile>
  </profiles>

</project>
