<?xml version='1.0' encoding='UTF-8'?>
<project xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://maven.apache.org/POM/4.0.0">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>org.capnproto</groupId>
        <artifactId>capnproto-java</artifactId>
        <version>${revision}</version>
    </parent>
    <artifactId>examples</artifactId>
    <packaging>jar</packaging>
    <name>capnproto-java examples</name>
    <description>capnproto-java examples</description>

    <dependencies>
        <dependency>
          <groupId>org.capnproto</groupId>
          <artifactId>capnp-jvm-core</artifactId>
        </dependency>

        <dependency>
          <groupId>org.capnproto</groupId>
          <artifactId>capnp-jvm-serialization-bytebuffer</artifactId>
        </dependency>
    </dependencies>

    <build>
      <plugins>
        <plugin>
          <artifactId>maven-antrun-plugin</artifactId>
          <executions>
            <execution>
              <id>generate-sources</id>
              <phase>generate-sources</phase>
              <configuration>
                <target>
                  <mkdir dir="src/main/generated"/>
                  <exec executable="capnp" failonerror="true">
                    <arg value="compile"/>
                    <arg value="-I"/>
                    <arg value="../compiler/src/main/schema/"/>
                    <arg value="--src-prefix=src/main/schema/"/>
                    <arg value="-o../capnpc-java:src/main/generated"/>
                    <arg value="src/main/schema/addressbook.capnp"/>
                  </exec>
                </target>
              </configuration>
              <goals>
                <goal>run</goal>
              </goals>
            </execution>
          </executions>
        </plugin>

        <plugin>
          <groupId>org.codehaus.mojo</groupId>
          <artifactId>build-helper-maven-plugin</artifactId>
          <executions>
            <execution>
              <id>add-generated-sources</id>
              <phase>generate-sources</phase>
              <goals>
                <goal>add-source</goal>
              </goals>
              <configuration>
                <sources>
                  <source>src/main/generated</source>
                </sources>
              </configuration>
            </execution>
          </executions>
        </plugin>
      </plugins>
    </build>
</project>
